repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: Check trailing whitespace
      - id: end-of-file-fixer
        name: Check end of file newlines
      - id: check-yaml
        name: Check YAML
      - id: check-added-large-files
        args: ['--maxkb=200']
        name: Check added large files
      - id: check-toml
        name: Check TOML
      - id: check-merge-conflict
        name: Check merge conflict
      - id: detect-private-key
        name: Check private keys

  - repo: local
    hooks:
      - id: ruff-lint
        entry: uv run ruff check --fix
        name: Check linting
        language: system
        types: [python]

      - id: ruff-format
        entry: uv run ruff format
        name: Check formatting
        language: system
        types: [python]

      - id: ty-type-check
        name: Check type safety
        entry: uv run ty check src tests
        language: system
        types: [python]

      - id: python-syntax-check
        name: Check for Python syntax errors
        entry: uv run python -m py_compile
        language: system
        types: [python]

      - id: c-check-syntax
        name: Check for C syntax errors
        entry: uv run sh -c 'gcc $(python3-config --includes) -fsyntax-only "$@"'
        language: system
        types: [c]

      - id: run-python-tests
        name: Run Python tests
        entry: uv run pytest tests/
        language: system
        types: [python]
        pass_filenames: false

      - id: run-c-tests
        name: Run C tests
        entry: uv run cd tests/c && rake test:all
        language: system
        types: [c]
